04-vue-cli
js-tasks-ru/vue-20220125_dan-ignatov pull request #10
Opened 2022-02-11 19:45 UTC by IgnatovDan

2022-02-11 19:45 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-11 21:32 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-12 16:05 UTC, ShGKme requested changes
В 03-UiDropdown1 требуется поменять хранение наличие иконки на вычисляемое свойство. Остальные задачи приняты.

2022-02-12 16:05 UTC, ShGKme commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
> +  },
На мой взгляд такие выражения лучше оставлять в шаблоне, чтобы сразу видеть вёрстку компонента.

2022-02-12 16:05 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToast.vue
> +
Имена с префиксом `The` обычно используют для компонентов, которые выводятся на странице один раз. Артикул The в англ. показывает, что это "конкретный" компонент, что у него будет "один конкретный экземпляр".

2022-02-12 16:05 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
По Style Guide не принято называть методы и другие свойства с нижнего подчёркивания.
Есть риск пересечения с приватными методами самого Vue.

[https://v3.vuejs.org/style-guide/#private-property-names-essential](https://v3.vuejs.org/style-guide/#private-property-names-essential)

Те функции, которые хочется иметь "приватными", вообще не связанными с Vue, можно выносить в обычные функции и не делать методом компонента. Чтобы делать "честно" приватные функции, и только конкретные публичными, можно использовать [expose](https://v3.vuejs.org/api/options-data.html#expose)

2022-02-12 16:05 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      );
findIndex + splice - тоже будет работать

2022-02-12 16:05 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +  },
👍

2022-02-12 16:05 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
>    </div>
Элемент `<template>` в шаблоне нужен, когда требуется для директив `v-if` или `v-for` обернуть несколько узлов сразу.

Если узел один, то директиву можно использовать непосредственно на ней без лишних обёрток.

2022-02-12 16:05 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
>    </div>
Оборачивать в `div` для добавления класса здесь также не обязательно. Классы можно вешать и на компоненты (если в них один корневой элемент).

2022-02-12 16:05 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
На мой взгляд такие объекты лучше держать в шаблоне. Они не слишком большие, но зато сразу будет видно вёрстку без перепрыгивания в JS часть компонента.

2022-02-12 16:05 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
`hasIconsInOptions` - это не самостоятельные данные компонента. Это всегда результат вычисления над `options`. При этом перевычислять его требуется только после изменения `options`, а не вообще любых параметров. Здесь лучше подходит вычисляемое свойство.

2022-02-12 16:05 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
В целом следует избегать отслеживания целиком `$props` или `$data`. Обычно это означает, что делается что-то не так, и на самом деле требуется следить всё-таки не за всем объектом.

2022-02-12 16:05 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    >
`style` можно заменить на `v-show="isDropDownOpened"` (проблема тестов, но всё-же так будет не так страшно выглядеть :) )

2022-02-12 16:06 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
Кстати, здесь отлично подойдёт метод some: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2022-02-12 20:34 UTC, IgnatovDan commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    >
заменил

2022-02-12 20:34 UTC, IgnatovDan commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
Да, хранить ссылку на объект вместо true/false не стоит.
И прошляпил полную вычисляемость, заменил на computed + some + true/false
watch для $props только ради validateProps.

2022-02-12 20:34 UTC, IgnatovDan commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    },
ok, переставил в разметку
Местами заменил на "v-show" и "v-if"

2022-02-12 20:34 UTC, IgnatovDan commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
>    </div>
Точно, <template> лишний для v-for.

"ToasterItem" тоже переставил.

2022-02-12 20:34 UTC, IgnatovDan commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +  },
:)

2022-02-12 20:34 UTC, IgnatovDan commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      );
ok
Заменил на indexOf/splice 
newItem.timeoutId = setTimeout(() => this.items.splice(this.items.indexOf(newItem), 1), this.closeToastTimeout);

2022-02-12 20:35 UTC, IgnatovDan commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
Точно, забыл про пересечения имен
Сделал совсем локальную функцию и вызов через "addToastItem.call(this, ToastTypes.success.name, message);"

2022-02-12 20:35 UTC, IgnatovDan commented on 04-vue-cli/02-TheToaster/components/TheToast.vue
> +
ok, переименовал

2022-02-12 20:35 UTC, IgnatovDan commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
> +  },
ok, перенес в разметку

2022-02-14 22:04 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
Конкретно в этом случае лучше использовать `expose`, и описывать метод, как обычный метод. Как функции снаружи обычно описывают функции, которые не привязываются к контексту экземпляра.

2022-02-14 22:09 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-02-14 22:09 UTC, ShGKme commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
>    </div>
Я бы оставил старый вариант - с объектом `{ 'form-group_inline': inline }` :)

2022-02-14 22:10 UTC, merged