Implement 05-vue-router
js-tasks-ru/vue-20220125_dan-ignatov pull request #11
Opened 2022-02-12 13:27 UTC by IgnatovDan

2022-02-12 13:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-12 16:31 UTC, ShGKme requested changes
В 01-AuthPages требуется убрать обработку клика...

2022-02-12 16:31 UTC, ShGKme commented on 05-vue-router/01-AuthPages/router/index.js
> +import PageRegister from '../views/PageRegister.vue';
Лучше использовать динамические импорты

2022-02-12 16:31 UTC, ShGKme commented on 05-vue-router/01-AuthPages/views/PageLogin.vue
> +        </div>
Сабмит формы может происходить не только кликом по кнопке. Это событие именно формы, и оно происходит:

- По клику на submit кнопки
- По нажатию Enter на десктопе
- По вызову метода `submit()` у формы

При этом без `.prevent` бы такой клик не отменил действия по умолчанию, которое на форме приводит к перезагрузке страницы.

В этой задаче обработчик события методом `handleSubmit` на форму уже установлен, поэтому всё работает. Требовалось только реализовать сам метод. Но в результате метод вызывается дважды. Аналогично на другой странице.

2022-02-12 20:35 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-12 21:13 UTC, IgnatovDan commented on 05-vue-router/01-AuthPages/views/PageLogin.vue
> +        </div>
Даже не знаю почему вчера я решил добавить обработчик на этот button.click.
Удалил.

2022-02-12 21:13 UTC, IgnatovDan commented on 05-vue-router/01-AuthPages/router/index.js
> +import PageRegister from '../views/PageRegister.vue';
ok, поправил на chunk + lazy import

2022-02-12 21:14 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-14 22:09 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-02-14 22:17 UTC, ShGKme approved these changes

2022-02-14 22:18 UTC, merged